# Ocean Depths theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#eef9ff"
base01 = "#cfe7f3"
base02 = "#a8cbe0"
base03 = "#5d839c"
base04 = "#436a8d"
base05 = "#2a4d68"
base06 = "#1b3447"
base07 = "#0a1722"
base08 = "#08718f"
base09 = "#ad571a"
base0A = "#8f6a17"
base0B = "#c41e45"
base0C = "#0a8068"
base0D = "#1d6fa0"
base0E = "#6f4cc4"
base0F = "#3a6b80"
