# Retro theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#f3ead6"
base01 = "#e8ddc5"
base02 = "#d7ccb6"
base03 = "#ab9f88"
base04 = "#847a6a"
base05 = "#564f43"
base06 = "#3a342b"
base07 = "#221f1a"
base08 = "#467036"
base09 = "#955714"
base0A = "#7c6311"
base0B = "#b53e30"
base0C = "#2b6f6b"
base0D = "#3a5e96"
base0E = "#74498f"
base0F = "#8a4f24"
