# Purple theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#ebe2f6"
base01 = "#cdb9e6"
base02 = "#b7a0d6"
base03 = "#9580bc"
base04 = "#7a619e"
base05 = "#473461"
base06 = "#322343"
base07 = "#191222"
base08 = "#1f7340"
base09 = "#8f4e0c"
base0A = "#7e6308"
base0B = "#b3253f"
base0C = "#0c7064"
base0D = "#3450bf"
base0E = "#8a3a8f"
base0F = "#6f34a3"
