# Purple theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#191222"
base01 = "#241a30"
base02 = "#322343"
base03 = "#473461"
base04 = "#7a619e"
base05 = "#b7a0d6"
base06 = "#cdb9e6"
base07 = "#ebe2f6"
base08 = "#6fb98a"
base09 = "#e0a85a"
base0A = "#ead07a"
base0B = "#e06a82"
base0C = "#52c6b0"
base0D = "#9aa8e8"
base0E = "#d98fd0"
base0F = "#b884e0"
