# Walnut theme - night variant
# Dark stained wood
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#160f09"
base01 = "#241910"
base02 = "#34261a"
base03 = "#4c3a28"
base04 = "#6e563e"
base05 = "#a8896a"
base06 = "#cbac8a"
base07 = "#f1ddc9"
base08 = "#7d9850"
base09 = "#c2701c"
base0A = "#d4ac3e"
base0B = "#dc5544"
base0C = "#5fa39a"
base0D = "#6f9ad0"
base0E = "#b083c4"
base0F = "#a87a48"
