# Cyberspace theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#e6ffff"
base01 = "#b6e8f0"
base02 = "#7fc4d6"
base03 = "#3f93ad"
base04 = "#226f8a"
base05 = "#13506b"
base06 = "#0c3047"
base07 = "#06121f"
base08 = "#00735a"
base09 = "#9a6a00"
base0A = "#5a7a00"
base0B = "#c80a4b"
base0C = "#007579"
base0D = "#0072c6"
base0E = "#8a2bd4"
base0F = "#b3267a"
