# Crystal Cave theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#f2edf8"
base01 = "#e1d8ed"
base02 = "#cbbce0"
base03 = "#9d85b9"
base04 = "#6e5494"
base05 = "#473262"
base06 = "#312047"
base07 = "#1a1226"
base08 = "#0a7361"
base09 = "#8a5f06"
base0A = "#7d620f"
base0B = "#7521c0"
base0C = "#0a786f"
base0D = "#a8325f"
base0E = "#5f37a6"
base0F = "#3a6f16"
