# Desert theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#f6f1e7"
base01 = "#ebe3d4"
base02 = "#d6ccba"
base03 = "#a89484"
base04 = "#80695a"
base05 = "#5b4a3c"
base06 = "#48392d"
base07 = "#291f17"
base08 = "#a8482a"
base09 = "#946411"
base0A = "#6f5a1d"
base0B = "#566638"
base0C = "#16756e"
base0D = "#b04e10"
base0E = "#9e4f4a"
base0F = "#477524"
