# Desert theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#291f17"
base01 = "#382b21"
base02 = "#48392d"
base03 = "#5b4a3c"
base04 = "#80695a"
base05 = "#a89484"
base06 = "#d2c6b4"
base07 = "#f6f1e7"
base08 = "#d2703f"
base09 = "#d99a3e"
base0A = "#e6c468"
base0B = "#8fa06f"
base0C = "#5bb3aa"
base0D = "#e57d35"
base0E = "#cd8b86"
base0F = "#9ec46a"
