# Nordic theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#eceff4"
base01 = "#e5e9f0"
base02 = "#d8dee9"
base03 = "#9099a9"
base04 = "#697588"
base05 = "#3b4252"
base06 = "#333b4a"
base07 = "#2e3440"
base08 = "#3f7375"
base09 = "#8a6718"
base0A = "#8f5f2c"
base0B = "#a3394a"
base0C = "#3a7184"
base0D = "#3f6b96"
base0E = "#834f7a"
base0F = "#516e3f"
