# Cyber theme - day variant
# Neon futuristic cyan
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#e6faf7"
base01 = "#c2eee8"
base02 = "#97dcd3"
base03 = "#5fb3a9"
base04 = "#33867d"
base05 = "#1b5b54"
base06 = "#0c3530"
base07 = "#03100f"
base08 = "#077a45"
base09 = "#8f5400"
base0A = "#6f6200"
base0B = "#b80e34"
base0C = "#06756f"
base0D = "#0f5cb5"
base0E = "#742db0"
base0F = "#09655c"
